site_name: LeetStats
theme:
  name: material
  language: en
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    # Palette toggle for light mode
    - scheme: default
      media: "(prefers-color-scheme: light)"
      primary: orange
      accent: green
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: deep orange
      accent: teal
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github
    logo: material/book-check-outline
  features:
    - search.suggest
    - search.highlight
    - search.share
    - navigation.footer
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand

repo_url: https://github.com/roma-glushko/leetstats
repo_name: roma-glushko/leetstats
copyright: Copyright &copy; 2025 - Present, <a href="https://www.romaglushko.com/">Roman Hlushko</a> & <a href="https://github.com/roma-glushko/leetstats">Friends</a>

markdown_extensions:
  - abbr
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

plugins:
  - search
  - tags:
      tags_file: problems/index.md
  - git-authors

extra_javascript:
  - js/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css

nav:
  - LeetStats: index.md
  - Problems:
    - problems/index.md
    - Easy:
      - problems/random-or-not.md
    - Hard:
      - problems/spell-checker.md
  - Solutions:
    - solutions/index.md
